// generated by stringer -type response; DO NOT EDIT

package sd

import "fmt"

const _response_name = "r1_readyr1_idle"

var _response_index = [...]uint8{8, 15}

func (i response) String() string {
	if i >= response(len(_response_index)) {
		return fmt.Sprintf("response(%d)", i)
	}
	hi := _response_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _response_index[i-1]
	}
	return _response_name[lo:hi]
}
