// generated by stringer -type sdStateCode; DO NOT EDIT

package sd

import "fmt"

const _sdStateCode_name = "sCommandsArgumentsChecksumsData"

var _sdStateCode_index = [...]uint8{8, 17, 26, 31}

func (i sdStateCode) String() string {
	if i >= sdStateCode(len(_sdStateCode_index)) {
		return fmt.Sprintf("sdStateCode(%d)", i)
	}
	hi := _sdStateCode_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _sdStateCode_index[i-1]
	}
	return _sdStateCode_name[lo:hi]
}
