// generated by stringer -type state; DO NOT EDIT

package sd

import "fmt"

const _state_name = "sCommandsArgumentsChecksumsData"

var _state_index = [...]uint8{8, 17, 26, 31}

func (i state) String() string {
	if i >= state(len(_state_index)) {
		return fmt.Sprintf("state(%d)", i)
	}
	hi := _state_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _state_index[i-1]
	}
	return _state_name[lo:hi]
}
